version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - internal

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    networks:
      - internal


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile
    networks:
      - internal

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/Discount.API/Dockerfile
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  portainer_data:

