version: '3.4'

services:
  catalog.api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
    ports:
      - "8000:80"

  basket.api:
    container_name: basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=redis:6379
    ports:
      - "8001:80"

