version: '3.4'

services:

  portainer:
    container_name: portainer
    ports:
      - 8080:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
    ports:
      - "8000:80"

  basket.api:
    container_name: basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=redis:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc
    ports:
      - "8001:80"


  discount.api:
    container_name: discount_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=postgis;Port=5432;Database=DiscountDb;User Id=postgres;Password=postgis@2022
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=postgis;Port=5432;Database=DiscountDb;User Id=postgres;Password=postgis@
    ports:
      - "8003:80"

